// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OurProject.API.Infra;

namespace OurProject.API.Migrations
{
    [DbContext(typeof(OurProjectContext))]
    partial class OurProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("OurProject.API.Domains.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("eventCounter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("eventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("eventDescription")
                        .HasColumnType("TEXT");

                    b.Property<bool>("eventEnroll")
                        .HasColumnType("INTEGER");

                    b.Property<string>("eventEnrollDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("eventMaxAge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("eventMinAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("eventName")
                        .HasColumnType("TEXT");

                    b.Property<string>("eventPersonList")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("OurProject.API.Domains.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("personBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("personMail")
                        .HasColumnType("TEXT");

                    b.Property<string>("personName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
